In [15]:
"""
An ant moves on a regular grid of squares that are coloured either black or white.
The ant is always oriented in one of the cardinal directions (left, right, up or down) and moves from square to adjacent square according to the following rules:
- if it is on a black square, it flips the color of the square to white, rotates 90 degrees counterclockwise and moves forward one square.
- if it is on a white square, it flips the color of the square to black, rotates 90 degrees clockwise and moves forward one square.

Starting with a grid that is entirely white, how many squares are black after 1018 moves of the ant?
"""
import numpy as np
import math
dim = 10
field = np.zeros((dim,dim), dtype=np.int)
white = 0
black = 1
print(field)
start_position = np.array([dim//2,dim//2])
looking_direction = np.array([1,0])
clockwise = -2*math.pi / 4
counterclockwise = -clockwise
def get_rotation_matrix(angle):
    return np.array([[math.cos(angle), -math.sin(angle)], 
                     [math.sin(angle),  math.cos(angle)]]).astype(int)
rotation_matrix_clockwise = get_rotation_matrix(clockwise)
rotation_matrix_counterclockwise = get_rotation_matrix(counterclockwise)
def color(position):
    return field[position[0], position[1]]
def flip(position):
    field[position[0], position[1]] = abs(field[position[0], position[1]] -1) # flips bit: abs(0 -1) = 1 | abs(1 -1) = 0
def move(position, looking_direction):
    flip(position)
    if color == white:        
        looking_direction = rotation_matrix_clockwise.dot(looking_direction)
    else:           
        looking_direction = rotation_matrix_counterclockwise.dot(looking_direction)
    return position + looking_direction, looking_direction

position = start_position
for i in range(5):
    position, looking_direction = move(position, looking_direction)
    print("position", position)
    print("looking", looking_direction)
    print(field)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
position [5 6]
looking [0 1]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
position [4 6]
looking [-1  0]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
position [4 5]
looking [ 0 -1]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0